/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java.roomready.payment;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import main.java.roomready.booking.gui.MainFrame;

/**
 *
 * @author philipmathewbobis
 */
public class ViewBookings extends javax.swing.JFrame {
    
    static String username;
    
    public ViewBookings() {
        initComponents();
        initializeComponents();
        showBookings();
    }

    public ViewBookings(String username){
        this.username = username;
    }
    
    private void initializeComponents(){
        // Initialize components here
        
        // Add a WindowlListener to the frame
        this.addWindowListener(new WindowAdapter(){
            public void windowClosing(WindowEvent e){
                // Call your validation here 
                boolean isValid = validateBeforeClose();
                if (!isValid){
                    // If validation fails or the user do unnecessary, cancel the window close operation
                    setDefaultCloseOperation(MainFrame.DO_NOTHING_ON_CLOSE);
                } else {
                    // If validation process or yes, will close the window
                    setDefaultCloseOperation(MainFrame.DISPOSE_ON_CLOSE);
                }
            }
        });
    }
    
     private boolean validateBeforeClose(){
            
       // Get the choice of the user if want to close the window or frame
       int choice = JOptionPane.showConfirmDialog(this, "Do you want to close?","Confirmation",JOptionPane.YES_NO_OPTION);
       return choice == JOptionPane.YES_OPTION; // return the value of choice of equal to YES_OPTION 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookings = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(218, 215, 205));

        bookings.setBackground(new java.awt.Color(218, 215, 205));
        bookings.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        bookings.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Room no", "Room type", "Floor level", "Hours", "Date", "Total Cost", "Payment Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        bookings.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                bookingsPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(bookings);
        if (bookings.getColumnModel().getColumnCount() > 0) {
            bookings.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel2.setBackground(new java.awt.Color(154, 51, 35));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Bookings");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(154, 51, 35));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 94, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 963, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private boolean buttonClicked = false;
    
    public void showBookings(){
        if (!buttonClicked){
        final String filePath = "src/main/java/resources/data/Payments.txt";
        String DELIMTER = "|";
        
        try(BufferedReader reader = new BufferedReader(new FileReader(filePath))){
            String line;
            DefaultTableModel tableModel = (DefaultTableModel) bookings.getModel();
            
            tableModel.setRowCount(0); // Clear existing data or rows in the table
            
            while((line = reader.readLine()) != null){
                String[] data = line.split("\\|");
                
                if (data.length >= 7){
                    String userName = data[0];
                    String roomType = data[3];
                    String floorLevel = data[5];
                    String date = data[6];
                    String paymentStatus = data[8];
                    int roomNo = Integer.parseInt(data[2]);
                    int hours = Integer.parseInt(data[4]);
                    double totalAmount = Double.parseDouble(data[7]);
                    
                    if(username.equals(userName)){ // validate current login account to only show the current users booking details
                        tableModel.addRow(new Object[]{roomNo,roomType,floorLevel,hours,date,totalAmount,paymentStatus});
                    }
                    
                }else {
                    JOptionPane.showMessageDialog(null, "Invalid data line", "Invalid", JOptionPane.WARNING_MESSAGE);
                }
            }
        }catch (IOException e){
            JOptionPane.showMessageDialog(null,"Error processing file","Error",JOptionPane.ERROR_MESSAGE);
        }
        buttonClicked = true;
        }else {
              JOptionPane.showMessageDialog(null, "You've already added the data. Clicking again will have no effect.","Already added", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    private void bookingsPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_bookingsPropertyChange
        DefaultTableCellRenderer dtcr = new DefaultTableCellRenderer();
        dtcr.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);
        DefaultTableModel tableModel = (DefaultTableModel) bookings.getModel();
        int columnCount = tableModel.getColumnCount();
        
        // Set the default cell renderer for all columns
        bookings.setDefaultRenderer(Object.class, dtcr);
        // set the renderer for columns
        for(int i = 0;i < columnCount;i++){
            bookings.getColumnModel().getColumn(i).setCellRenderer(dtcr);
        }
        
        bookings.setRowHeight(100);
        
        // Set preffered size on specific columns
        bookings.getColumnModel().getColumn(1).setPreferredWidth(230);
        bookings.getColumnModel().getColumn(3).setPreferredWidth(70);
        bookings.getColumnModel().getColumn(4).setPreferredWidth(100);
        bookings.getColumnModel().getColumn(5).setPreferredWidth(80);
    }//GEN-LAST:event_bookingsPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewBookings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bookings;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
