 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java.roomready.admin.gui;

import main.java.roomready.authentication.AdminAuthenticationManager;

import javax.swing.JOptionPane;


import main.java.roomready.customer.dashboardtesting.Form1;
import main.java.roomready.customer.dashboardtesting.Form2;
import main.java.roomready.customer.dashboardtesting.Form3;
import main.java.roomready.customer.dashboardtesting.Form4;
import main.java.roomready.customer.dashboardtesting.Form5;

import main.java.roomready.room.gui.RoomManagement;

/**
 *
 * @author Miguel
 */
public class AdminPanel extends javax.swing.JFrame {
    private AdminAuthenticationManager authManager;
    /**
     * Creates new form AdminPanel
     */
    public AdminPanel(String fullName) {
        initComponents();
        authManager = new AdminAuthenticationManager();
        accountName.setText(fullName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel20 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        accountName = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        roomManagementButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        paymentButton = new javax.swing.JButton();
        guestManagementButton = new javax.swing.JButton();
        notificationButton = new javax.swing.JButton();
        systemSettingsButton = new javax.swing.JButton();
        bookingManagementButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        tabbedPane = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Dashboard");
        setBackground(new java.awt.Color(0, 0, 0));
        setLocation(new java.awt.Point(30, 50));
        setPreferredSize(new java.awt.Dimension(1250, 640));
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        jPanel20.setBackground(new java.awt.Color(240, 232, 221));
        jPanel20.setPreferredSize(new java.awt.Dimension(400, 600));

        jPanel19.setBackground(new java.awt.Color(204, 204, 204));
        jPanel19.setPreferredSize(new java.awt.Dimension(400, 70));

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/java/resources/images/Wow Logo Dashboard.png"))); // NOI18N
        jLabel22.setFocusable(false);
        jLabel22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel22.setMaximumSize(new java.awt.Dimension(55, 55));
        jLabel22.setMinimumSize(new java.awt.Dimension(55, 55));
        jLabel22.setPreferredSize(new java.awt.Dimension(55, 55));
        jLabel22.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel23.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("ROOMREADY");

        jLabel25.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 102, 102));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("HOTEL BOOKING SYSTEM");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addGap(0, 0, 0)
                .addComponent(jLabel25)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/java/resources/images/hotel-manager 64px.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Hotel Administrator");

        accountName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        accountName.setForeground(new java.awt.Color(51, 51, 51));
        accountName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accountName.setText("First Name M.I Last Name");

        jSeparator1.setBackground(new java.awt.Color(51, 51, 51));

        roomManagementButton.setBackground(new java.awt.Color(204, 204, 204));
        roomManagementButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        roomManagementButton.setForeground(new java.awt.Color(154, 51, 35));
        roomManagementButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/java/resources/images/icons8-open-door-32.png"))); // NOI18N
        roomManagementButton.setText("ROOM MANAGEMENT");
        roomManagementButton.setFocusable(false);
        roomManagementButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        roomManagementButton.setIconTextGap(10);
        roomManagementButton.setPreferredSize(new java.awt.Dimension(75, 75));
        roomManagementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomManagementButtonActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(154, 51, 35));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/java/resources/images/business-report 32px.png"))); // NOI18N
        jButton2.setText("REPORT GENERATION");
        jButton2.setFocusable(false);
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton2.setIconTextGap(10);
        jButton2.setPreferredSize(new java.awt.Dimension(75, 75));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        paymentButton.setBackground(new java.awt.Color(204, 204, 204));
        paymentButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        paymentButton.setForeground(new java.awt.Color(154, 51, 35));
        paymentButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/java/resources/images/card-payment 32px.png"))); // NOI18N
        paymentButton.setText("PAYMENT PROCESSING");
        paymentButton.setFocusable(false);
        paymentButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        paymentButton.setIconTextGap(10);
        paymentButton.setPreferredSize(new java.awt.Dimension(75, 75));
        paymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentButtonActionPerformed(evt);
            }
        });

        guestManagementButton.setBackground(new java.awt.Color(204, 204, 204));
        guestManagementButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        guestManagementButton.setForeground(new java.awt.Color(154, 51, 35));
        guestManagementButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/java/resources/images/guests 32px.png"))); // NOI18N
        guestManagementButton.setText("GUEST MANAGEMENT");
        guestManagementButton.setFocusable(false);
        guestManagementButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        guestManagementButton.setIconTextGap(10);
        guestManagementButton.setPreferredSize(new java.awt.Dimension(75, 75));
        guestManagementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guestManagementButtonActionPerformed(evt);
            }
        });

        notificationButton.setBackground(new java.awt.Color(204, 204, 204));
        notificationButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        notificationButton.setForeground(new java.awt.Color(154, 51, 35));
        notificationButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/java/resources/images/notification 32px.png"))); // NOI18N
        notificationButton.setText("NOTIFICATION");
        notificationButton.setFocusable(false);
        notificationButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        notificationButton.setIconTextGap(10);
        notificationButton.setPreferredSize(new java.awt.Dimension(75, 75));
        notificationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notificationButtonActionPerformed(evt);
            }
        });

        systemSettingsButton.setBackground(new java.awt.Color(204, 204, 204));
        systemSettingsButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        systemSettingsButton.setForeground(new java.awt.Color(154, 51, 35));
        systemSettingsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/java/resources/images/icons8-settings-32.png"))); // NOI18N
        systemSettingsButton.setText("SYSTEM SETTINGS");
        systemSettingsButton.setFocusable(false);
        systemSettingsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        systemSettingsButton.setIconTextGap(10);
        systemSettingsButton.setPreferredSize(new java.awt.Dimension(75, 75));
        systemSettingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                systemSettingsButtonActionPerformed(evt);
            }
        });

        bookingManagementButton.setBackground(new java.awt.Color(204, 204, 204));
        bookingManagementButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bookingManagementButton.setForeground(new java.awt.Color(154, 51, 35));
        bookingManagementButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/java/resources/images/calendar 32.png"))); // NOI18N
        bookingManagementButton.setText("BOOKING MANAGEMENT");
        bookingManagementButton.setFocusable(false);
        bookingManagementButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        bookingManagementButton.setIconTextGap(10);
        bookingManagementButton.setPreferredSize(new java.awt.Dimension(75, 75));
        bookingManagementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingManagementButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(116, 116, 116))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                                .addComponent(accountName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)))
                        .addGroup(jPanel20Layout.createSequentialGroup()
                            .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                .addComponent(notificationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(systemSettingsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(guestManagementButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(paymentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(roomManagementButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bookingManagementButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator1))
                            .addGap(28, 28, 28))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accountName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(bookingManagementButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roomManagementButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paymentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guestManagementButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(systemSettingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notificationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setFocusable(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(850, 600));
        jPanel2.setLayout(null);

        jPanel21.setBackground(new java.awt.Color(154, 51, 35));
        jPanel21.setPreferredSize(new java.awt.Dimension(200, 70));

        jLabel24.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("WELCOME TO THE ADMIN DASHBOARD");

        logoutButton.setBackground(new java.awt.Color(154, 51, 35));
        logoutButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/java/resources/images/icons8-logout-32.png"))); // NOI18N
        logoutButton.setText("LOGOUT");
        logoutButton.setToolTipText("");
        logoutButton.setBorder(null);
        logoutButton.setFocusable(false);
        logoutButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        logoutButton.setIconTextGap(10);
        logoutButton.setPreferredSize(new java.awt.Dimension(75, 75));
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 379, Short.MAX_VALUE)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel24)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel21);
        jPanel21.setBounds(-9, 1, 910, 70);

        tabbedPane.setBackground(new java.awt.Color(255, 255, 255));
        tabbedPane.setForeground(new java.awt.Color(204, 204, 204));
        tabbedPane.setPreferredSize(new java.awt.Dimension(850, 400));
        jPanel2.add(tabbedPane);
        tabbedPane.setBounds(-9, 39, 910, 660);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 897, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // Display the confirmation dialog
        int option = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Logout Confirmation", JOptionPane.YES_NO_OPTION);
        
        // Check the user's choice
        if(option == JOptionPane.YES_OPTION){
        
        // Close the current login menu form
        this.dispose();
        
        // Open the customer login form when the button is clicked
        AdminLogin adminLogin = new AdminLogin(authManager); // Create an instance of the CustomerLogin;
        adminLogin.setVisible(true); // Show the customer login form
        }
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void paymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentButtonActionPerformed
        tabbedPane.removeAll();
        tabbedPane.addTab("Form 3", new Form3());
    }//GEN-LAST:event_paymentButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void roomManagementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomManagementButtonActionPerformed
        tabbedPane.removeAll();
        tabbedPane.addTab("Room Management", new RoomManagement());
    }//GEN-LAST:event_roomManagementButtonActionPerformed

    private void systemSettingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_systemSettingsButtonActionPerformed
        // Close the current dashboard
        this.dispose();

        // Open the admin registration form when the button is clicked
        AdminRegistration adminRegistration = new AdminRegistration(authManager); // Create an instance of the AdminRegistration;
        adminRegistration.setVisible(true); // Show the admin registration form                                       
    }//GEN-LAST:event_systemSettingsButtonActionPerformed

    private void notificationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificationButtonActionPerformed
        tabbedPane.removeAll();
        tabbedPane.addTab("Form 5", new Form5());
    }//GEN-LAST:event_notificationButtonActionPerformed

    private void bookingManagementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingManagementButtonActionPerformed
        tabbedPane.removeAll();
        tabbedPane.addTab("Form 1", new Form1());
    }//GEN-LAST:event_bookingManagementButtonActionPerformed

    private void guestManagementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guestManagementButtonActionPerformed
        tabbedPane.removeAll();
        tabbedPane.addTab("Form 4", new Form4());
    }//GEN-LAST:event_guestManagementButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        String fullName =  "";
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel(fullName).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountName;
    private javax.swing.JButton bookingManagementButton;
    private javax.swing.JButton guestManagementButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton notificationButton;
    private javax.swing.JButton paymentButton;
    private javax.swing.JButton roomManagementButton;
    private javax.swing.JButton systemSettingsButton;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
