/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.java.roomready.customer.dashboardtesting;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Miguel
 */
public class Form4 extends javax.swing.JPanel {

    /**
     * Creates new form Form4
     */
    public Form4() {
        initComponents();
        loadDataFromFile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        deleteButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 0));

        jPanel1.setBackground(new java.awt.Color(218, 215, 205));

        jPanel2.setBackground(new java.awt.Color(218, 215, 205));

        deleteButton.setText("Delete Account");
        deleteButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("User Management");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        userTable.setBackground(new java.awt.Color(218, 215, 205));
        userTable.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Account no", "Username", "Account Name", "Gender", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        userTable.setRowHeight(30);
        userTable.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                userTablePropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(userTable);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/java/resources/images/wow.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        String filePath = "src/main/java/resources/data/customers.txt";
        String tempFilePath = filePath + ".tmp";
        boolean foundAccount = false;

        String input2 = JOptionPane.showInputDialog(null, "Enter account name:", "Delete Account", JOptionPane.QUESTION_MESSAGE);

        if (input2 == null || input2.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Username is empty or not provided.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Use try-with-resources to automatically close the resources
        try (BufferedReader reader = new BufferedReader(new FileReader(filePath));
            BufferedWriter writer = new BufferedWriter(new FileWriter(tempFilePath))) {

            String currentLine;
            while ((currentLine = reader.readLine()) != null) {
                String[] parts = currentLine.split("\\|");
                if (!input2.equals(parts[1])) {
                    writer.write(currentLine);
                    writer.newLine(); // Create a new line
                } else {
                    foundAccount = true;
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        if (!foundAccount) {
            JOptionPane.showMessageDialog(null, "Account with account name " + input2 + " not found.", "Account not found", JOptionPane.WARNING_MESSAGE);
            return; // Stop further execution
        }

        // Transfer the updated content back to the original file
        try (BufferedReader reader = new BufferedReader(new FileReader(tempFilePath));
            BufferedWriter writer = new BufferedWriter(new FileWriter(filePath))) {

            String currentLine;
            while ((currentLine = reader.readLine()) != null) {
                writer.write(currentLine);
                writer.newLine();
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        // Delete the temporary file after transferring the updated content to the original file
        File tempFile = new File(tempFilePath);
        if (!tempFile.delete()) {
            JOptionPane.showMessageDialog(null, "Could not delete the temporary file", "FAILED", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Successfully Deleted", "Success", JOptionPane.PLAIN_MESSAGE);
        }

        // Clear existing rows from the table model
        DefaultTableModel model = (DefaultTableModel) userTable.getModel();
        model.setRowCount(0);

        // Reload updated data and add it to the table model
        loadDataFromFile();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void loadDataFromFile(){
            final String filePath = "src/main/java/resources/data/customers.txt";
            final String DELIMITER = "|";
            
            try(BufferedReader reader = new BufferedReader(new FileReader(filePath))){
                String line;
                DefaultTableModel model = (DefaultTableModel) userTable.getModel();
                
                while ((line = reader.readLine()) != null){
                    String[] data = line.split("\\" + DELIMITER);
                    
                    if (data.length >= 4){
                        String accountNo = data[0];
                        String userName = data[1];
                        String accountName = data[3];
                        String gender = data[4];
                        String email = data[5];
                        int age = 0;
                        if (data[0].matches("\\d+") && data[3].matches("\\d+")){
                            
                            age = Integer.parseInt(data[3]);
                        }
                        
                        model.addRow(new Object[]{accountNo,userName,accountName,gender,email});
                    }else {
                        JOptionPane.showMessageDialog(null, "Invalid data line", "Invalid", JOptionPane.WARNING_MESSAGE);
                    }
                }
            }catch (IOException e){
                e.printStackTrace();
            }
        
    }
    
    private void userTablePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_userTablePropertyChange
        DefaultTableCellRenderer dtcr = new DefaultTableCellRenderer();
        dtcr.setHorizontalAlignment(DefaultTableCellRenderer.LEFT);

        // Set the default cell renderer for all columns
        userTable.setDefaultRenderer(Object.class, dtcr);

    }//GEN-LAST:event_userTablePropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables
}
